version: 2

sources:
  - name: recommmender_system_raw
    description: "machine learning raw tables"
    database: mlops
    schema: source
    tables:
      - name: ratings
      - name: movies
      - name: user
